simple_django/forms/core/urls.py
from django.urls import path
from core.views import IndexView, GroupsAndStudentsView, RegistrationView, contactView, successView, TeacherCreateView, StudentCreateView, GroupCreateView, TeacherUpdateView, GroupUpdateView, StudentUpdateView, GroupDeleteView, StudentDeleteView, TeacherDeleteView, AllTeachersView, TeachersView, StudentsView

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('teachers/', TeachersView.as_view(), name='teachers'),
    path('allteachers/', AllTeachersView.as_view(), name='allteachers'),
    path('students/', StudentsView.as_view(), name='students'),
    path('create-teacher/', TeacherCreateView.as_view(), name='create-teacher'),
    path('create-student/', StudentCreateView.as_view(), name='create-student'),
    path('create-group/', GroupCreateView.as_view(), name='create-group'),
    path('update-teacher/<str:username>/', TeacherUpdateView.as_view(), name='update-teacher'),
    path('update-group/<int:group_id>/', GroupUpdateView.as_view(), name='update-group'),
    path('update-student/<int:student_id>/', StudentUpdateView.as_view(), name='update-student'),
    path('delete-student/<int:student_id>/', StudentDeleteView.as_view(), name='delete-student'),
    path('delete-group/<int:group_id>/', GroupDeleteView.as_view(), name='delete-group'),
    path('delete-teacher/<str:username>/', TeacherDeleteView.as_view(), name='delete-teacher'),
    path('contact/', contactView, name='contact'),
    path('success/', successView, name='success'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('groupsandstudents/<str:username>/', GroupsAndStudentsView.as_view(), name='groupsandstudents')
]

simple_django/forms/forms/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include(("core.urls", "core"), namespace='main'))
]

simple_django/forms/core/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model


class MyUser(AbstractUser):
    pass


class Currency(models.Model):
    CCY_USD = 1
    CCY_EUR = 2
    CCY_RUR = 3

    CCY_CHOICES = (
        (CCY_USD, 'USD'),
        (CCY_EUR, 'EUR'),
        (CCY_RUR, 'RUR')
    )

    ccy = models.PositiveSmallIntegerField(choices=CCY_CHOICES)
    buy_price = models.DecimalField(max_digits=5, decimal_places=2)
    sell_price = models.DecimalField(max_digits=5, decimal_places=2)
    title = models.CharField(max_length=255, null=True)
    created = models.DateTimeField(auto_now_add=True)

    @classmethod
    def convert_str_to_choice(cls, choice_name):
        choices = dict(map(reversed, cls.CCY_CHOICES))
        if choice_name in choices:
            return choices[choice_name]


class Logger(models.Model):
    time_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    request_path = models.CharField(max_length=255, null=True)
    request_method = models.CharField(max_length=255, null=True)
    execution_time = models.FloatField(null=True)

    class Meta:
        verbose_name = "Log"
        verbose_name_plural = "Logs"

    def __str__(self):
        return self.request_path


class Student(models.Model):
    phone = models.CharField(max_length=255, verbose_name="Телефон", null=True)
    first_name = models.CharField(max_length=255, verbose_name="Имя")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия", null=True)
    age = models.IntegerField(null=True)

    class Meta:
        verbose_name = "Студент"
        verbose_name_plural = "Студенты"

    def clean(self):
        self.first_name = self.first_name.capitalize()
        self.last_name = self.last_name.capitalize()

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Group(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название группы")
    students = models.ManyToManyField("core.Student", blank=True)
    teacher = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"

    def __str__(self):
        return self.name


def send_notify(instance, **kwargs):
    from core.utils import notify
    notify(instance)


pre_save.connect(send_notify, sender=Student)
pre_save.connect(send_notify, sender=MyUser)

simple_django/forms/core/forms.py
from django import forms
from core.fields import PhoneField
from core.models import Group, Student
from django.contrib.auth import get_user_model


class RegistrationForm(forms.ModelForm):
    password_confirm = forms.CharField(widget=forms.widgets.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'password', 'password_confirm')
        widgets = {
            'password': forms.widgets.PasswordInput()
        }

    def clean_password_confirm(self):
        if self.cleaned_data['password_confirm'] != self.cleaned_data['password']:
            raise forms.ValidationError("Passwords do not match")
        return self.cleaned_data['password']

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)

        user.set_password(self.cleaned_data['password'])
        user.save()

        return user


class ContactUS(forms.Form):
    title = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()


class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = '__all__'
        widgets = {
            'students': forms.widgets.CheckboxSelectMultiple()
        }


class StudentForm(forms.ModelForm):
    phone = PhoneField()

    class Meta:
        model = Student
        fields = '__all__'

simple_django/forms/core/views.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.views.generic import FormView
from django.contrib.auth.models import User
from django.db.models import Avg, Max, Min, Count
from django.urls.base import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.mail import BadHeaderError
from core.forms import GroupForm, StudentForm, ContactUS, RegistrationForm
from core.models import Student, Group, get_user_model
from core.tasks import send_mail_celery


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)

        groups = Group.objects.all().values('id', 'name', 'teacher').annotate(
            student_count=Count('students'),
            student_avg=Avg('students__age'),
            student_max=Max('students__age'),
            student_min=Min('students__age'),
        )

        teachers = get_user_model().objects.all()
        context['count_words'] = self.request.GET.get('count_words', '0')

        return {
                'teachers': teachers,
                'groups': groups,
                'count_words': context['count_words']
            }


class GroupsAndStudentsView(TemplateView):
    template_name = "groupsandstudents.html"

    def get_context_data(self, **kwargs):
        groups = Group.objects.filter(teacher__username=kwargs['username']).prefetch_related('students')
        return {
            'groups': groups,
        }


class RegistrationView(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = 'registration.html'
    success_url = reverse_lazy('main:home')


def contactView(request):
    if request.method == 'GET':
        form = ContactUS()
    else:
        form = ContactUS(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            try:
                send_mail_celery.delay(title, sender, message)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('main:success')
    return render(request, "contact.html", {'form': form})


def successView(request):
    return HttpResponse('Success! Thank you for your message.')


class TeachersView(TemplateView):
    template_name = "teachers.html"

    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        groups = Group.objects.all().values('id', 'name', 'teacher')

        return {
            'groups': groups,
        }


class AllTeachersView(TemplateView):
    template_name = "allteachers.html"

    def get_context_data(self, **kwargs):
        allteachers = get_user_model().objects.all()
        return {
            'allteachers': allteachers
        }


class StudentsView(TemplateView):
    template_name = "students.html"

    def get_context_data(self, **kwargs):
        students = Student.objects.all()
        return {
            'students': students
        }


class TeacherCreateView(CreateView):
    template_name = 'create.html'

    success_url = reverse_lazy('main:teachers')
    model = get_user_model()
    fields = '__all__'


class StudentCreateView(CreateView):
    template_name = 'create.html'

    success_url = reverse_lazy('main:teachers')
    model = Student
    fields = '__all__'


class GroupCreateView(FormView):
    template_name = 'create.html'

    form_class = GroupForm
    success_url = reverse_lazy('main:teachers')

    def form_valid(self, form):
        form.save()
        return super(GroupCreateView, self).form_valid(form)


class TeacherUpdateView(UpdateView):
    template_name = 'update_teacher.html'

    success_url = reverse_lazy('main:allteachers')
    model = get_user_model()
    form_class = RegistrationForm
    slug_field = "username"
    slug_url_kwarg = "username"


class StudentUpdateView(UpdateView):
    template_name = 'update_student.html'

    success_url = reverse_lazy('main:students')
    model = Student
    form_class = StudentForm
    pk_url_kwarg = 'student_id'


class GroupUpdateView(UpdateView):
    template_name = 'update_group.html'

    success_url = reverse_lazy('main:teachers')
    model = Group
    form_class = GroupForm
    pk_url_kwarg = 'group_id'


class TeacherDeleteView(DeleteView):
    template_name = 'delete.html'

    model = get_user_model()
    success_url = reverse_lazy('main:allteachers')
    slug_field = "username"
    slug_url_kwarg = "username"


class GroupDeleteView(DeleteView):
    template_name = 'delete.html'

    model = Group
    pk_url_kwarg = 'group_id'
    success_url = reverse_lazy('main:teachers')


class StudentDeleteView(DeleteView):
    template_name = 'delete.html'

    model = Student
    pk_url_kwarg = 'student_id'
    success_url = reverse_lazy('main:students')

simple_django/forms/core/templates/allteachers.html
{% extends "base.html" %}
{% block content %}
            <div class="col-md-8">
                <form method="get">
                    <div class="row">
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:teachers' %}">Back</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <table class="table">
                        <tr>
                            <th>Teacher</th>
                        </tr>
                        {% for teacher in allteachers %}
                            <tr>
                                <td>{{ teacher }}</td>
                                <td>
                                    <a class="btn btn-primary" href="{% url 'main:update-teacher' teacher.username %}">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
{% endblock content %}

simple_django/forms/core/templates/base.html
{% load static %}
<html>
    <head>
             <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    </head>
    <body>
        <br>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    </body>
</html>

simple_django/forms/core/templates/contact.html
{% extends "base.html" %}
{% block content %}
    <h1>Contact Us</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-actions">
          <button type="submit">Send</button>
        </div>
    </form>
{% endblock content %}

simple_django/forms/core/templates/create.html
{% extends "base.html" %}
{% block content %}
            <form role="form" method="post">{% csrf_token %}
                {{ form }}
                <div class="form-group">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
{% endblock content %}

simple_django/forms/core/templates/delete.html
{% extends "base.html" %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock content %}

simple_django/forms/core/templates/groupsandstudents.html
{% extends "base.html" %}
{% block content %}
            <div class="col-md-8">
                <form method="get">
                    <div class="row">
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:home' %}">Main</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <table class="table">
                        {% for group in groups %}
                            <tr>
                                <th>Group</th>
                            </tr>
                            <tr>
                                <td>{{group.name}}</td>
                            </tr>
                            <th>students</th>
                            {% for students in group.students.all %}
                                    <tr>
                                        <td>{{students}}</td>
                                    </tr>
                            {% endfor %}
                        {% endfor %}
                    </table>
                </div>
            </div>
{% endblock content %}

simple_django/forms/core/templates/index.html
{% extends "base.html" %}
{% load static custom_stuff %}
{% block content %}
            <div class="col-md-12">
                <form method="get">
                    <div class="row">
                        <div class="col-md-5">
                            <a class="btn btn-primary" href="{% url 'main:students' %}">STUDENTS</a>
                        </div>
                        <div class="col-md-5">
                            <a class="btn btn-primary" href="{% url 'main:teachers' %}">Teachers</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br><br>
        <div class="container">
            <h1>MASSIVE</h1>
            {{ massive|mass_filter }}
            <h1>COUNT WORDS IN STRING</h1>
            <form>
                <input type="text" name="count_words">
                {{ count_words|countw_filter }}
            </form>
            <h1>TRACKS</h1>
                {% for track in tracks %}
                    {% if track.track_duration == '3:33' and track.name == 'Serendipity' %}
                        {{ track }}
                    {% endif %}
                {% endfor %}
            <h1>TEACHERS</h1>
                {% random_teachers %}
            <div class="row">
                <div class="col-6">
                    <table class="table">
                        <tr>
                            <th>TeacherUsers</th>
                        </tr>
                        {% for teacher in teachers %}
                            <tr>
                                <td>{{teacher}}</td>
                                <td>
                                    <a class="btn btn-primary" href="{% url 'main:groupsandstudents' teacher.username %}">GroupsAndStudents</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <table class="table">
                        <tr>
                            <th>Group</th>
                            <th>Number_of_students</th>
                            <th>AVG_age_of_students</th>
                            <th>MAX_age_of_students</th>
                            <th>MIN_age_of_students</th>
                            <th>Teacher</th>
                        </tr>
                        {% for group in groups %}
                            <tr>
                                <td>{{group.name}}</td>
                                <td>{{group.student_count}}</td>
                                <td>{{group.student_avg}}</td>
                                <td>{{group.student_max}}</td>
                                <td>{{group.student_min}}</td>
                                <td>{{group.teacher}}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
{% endblock content %}

simple_django/forms/core/templates/registration.html
{% extends "base.html" %}
{% block content %}
            <form role="form" method="post">{% csrf_token %}
                {{ form }}
                <div class="form-group">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
{% endblock content %}

simple_django/forms/core/templates/students.html
{% extends "base.html" %}
{% block content %}
            <div class="col-md-8">
                <form method="get">
                    <div class="row">
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:home' %}">Main</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <table class="table">
                        <tr>
                            <th>Student_first_name</th>
                            <th>Student_last_name</th>
                        </tr>
                        {% for student in students %}
                            <tr>
                                <td>{{student.first_name}}</td>
                                <td>{{student.last_name}}</td>
                                <td>
                                    <a class="btn btn-primary" href="{% url 'main:update-student' student.id %}">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
{% endblock content %}

simple_django/forms/core/templates/teachers.html
{% extends "base.html" %}
{% block content %}
            <div class="col-md-12">
                <form method="get">
                    <div class="row">
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:home' %}">MAIN</a>
                        </div>
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:allteachers' %}">All_TEACHERS</a>
                        </div>
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:registration' %}">Add_TeacherUser</a>
                        </div>
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:create-group' %}">Add_Group</a>
                        </div>
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:create-student' %}">Create_Student</a>
                        </div>
                        <div class="col-md-2">
                            <a class="btn btn-primary" href="{% url 'main:students' %}">Edit_STUDENTS</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br><br>
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <table class="table">
                        <tr>
                            <th>Group</th>
                            <th>Teacher</th>
                        </tr>
                        {% for group in groups %}
                            <tr>
                                <td>{{group.name}}</td>
                                <td>{{group.teacher}}</td>
                                <td>
                                    <a class="btn btn-primary" href="{% url 'main:update-group' group.id %}">Edit</a>
                                    <a class="btn btn-primary" href="{% url 'main:delete-group' group.id %}">Remove</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
{% endblock content %}

simple_django/forms/core/templates/update_group.html
{% extends "base.html" %}
{% block content %}
    <form role="form" method="post">{% csrf_token %}
        {{ form }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
{% endblock content %}

simple_django/forms/core/templates/update_student.html
{% extends "base.html" %}
{% block content %}
            <form role="form" method="post">{% csrf_token %}
                {{ form }}
                <div class="form-group">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <a class="btn btn-primary" href="{% url 'main:delete-student' student.id %}">Delete</a>
                </div>
            </form>
{% endblock content %}

simple_django/forms/core/templates/update_teacher.html
{% extends "base.html" %}
{% block content %}
            <form role="form" method="post">{% csrf_token %}
                {{ form }}
                <div class="form-group">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <a class="btn btn-primary" href="{% url 'main:delete-teacher' myuser.username %}">Delete</a>
                </div>
            </form>
{% endblock content %}